### ISSUE TITLE
关于geosite.dat

### ISSUE THREAD

**Issue by dnvcupid** [KyonLi/asuswrt-v2ray#1]
首先我是小白，可能有些问题比较愚蠢，望见谅

`pkg_file/opt/bin/v2ray/geosite.dat 中预置两个域名表：gfw和googlecn`

我看了下`v2ray-SiteDAT`生成配置里面有cn、direct、proxy、reject四个文件，使用`v2ray-SiteDAT`生成geosite.dat 的好像没有说到域名表的事情（gfw和googlecn）

还有`pkg_file/opt/bin/v2ray/geosite.dat`这个dat是gfwlist完整域名的吗，如果是完整的就不用自己生成了，我看和gfwlist文件大小相差挺多的，大神会维护geosite.dat的更新吗

（如果我想自己生成）
gfw说的是gfwlist吧，怎么提取gfwlist里面的域名来生成自己的geosite.dat，gfwlist里面的哪些域名是放在v2ray-SiteDAT对应的配置文件（cn、direct、proxy、reject）里面的，gfwlist里面有些域名前面有`||`、`|`、`@@||`、`@@|`、`.`这些都是怎么区分的吗，看了下像我这种小白想自己生成geosite.dat基本上是没什么可能

**Comment by KyonLi** [comment]
> 我看了下v2ray-SiteDAT生成配置里面有cn、direct、proxy、reject四个文件，使用v2ray-SiteDAT生成geosite.dat 的好像没有说到域名表的事情（gfw和googlecn）

v2ray-SiteDAT文件名对应dat里的域名表，新建gfw和googlecn两个文件就会多出这两个表。

> 怎么提取gfwlist里面的域名来生成自己的geosite.dat

可以使用 https://github.com/cokebar/gfwlist2dnsmasq 将gfwlist规则转换为域名列表。

**Comment by dnvcupid** [comment]
大佬不介意我再问几个小白问题吧

v2ray-SiteDAT配置文件里面的cn、direct、proxy、reject删除，新建gfw、googlecn，gfw放的是gfwlist域名（sh gfwlist2dnsmasq.sh -l -o gfwlist.txt ）这个结果得到的就是gfw对吧。

`googlecn使用 @felixonmars 的 dnsmasq-china-list 中Google部分`这个是只使用里面google的域名，其他的不需要是这个意思吗

`已激活Download Master可以使用ipkg（如不需要Download Master可以在激活后卸载）；`

固件（3.0.0.4.384_20379）这个ipkg版本是ipkg version 0.99.163，好像是没有ipkg-build（ipkg-build: not found）

再问一下`安装 ipkg-utils`这个怎么安装吗，下载了不会装，里面有个setup.py，需要先安装ipkg install python27?

**Comment by KyonLi** [comment]
预置规则只是参考，可以参考v2ray文档写自己的路由策略

> 再问一下安装 ipkg-utils这个怎么安装

```bash
cd ~
git clone https://github.com/KyonLi/asuswrt-v2ray.git
wget http://ipkg.nslu2-linux.org/sources/ipkg-utils-1.7.tar.gz
tar -zxvf ipkg-utils-1.7.tar.gz

cd asuswrt-v2ray
../ipkg-utils-1.7/ipkg-build -c -o admin -g root pkg_file ~/
```

**Comment by dnvcupid** [comment]
admin@RT-AC88U:/tmp/asuswrt-v2ray/ipkg-utils-1.7# ipkg-build -c -o admin -g root /tmp/asuswrt-v2ray/pkg_file /
-sh: ipkg-build: not found

**Comment by dnvcupid** [comment]
装了个ubuntu在里面编译了

安装

Ipkg: extract_archive: /CONTROL/: Read-only file system
Ipkg: /CONTROL/prerm: No such file or directory
Ipkg: /CONTROL/control: No such file or directory
Ipkg: /CONTROL/conffiles: No such file or directory
Ipkg: /CONTROL/postinst: No such file or directory
Configuring v2ray
Successfully terminated.

**Comment by KyonLi** [comment]
[release](https://github.com/KyonLi/asuswrt-v2ray/releases/latest) 版本可以安装吗？

**Comment by dnvcupid** [comment]
出错也可以正常安装，能正常翻墙，原来有release版本的。。我一直以为要自己编译，折腾了那么久
