### ISSUE TITLE
start-stop-daemon错误？

### ISSUE THREAD

**Issue by dnvcupid** [KyonLi/asuswrt-v2ray#2]
Upgrading v2ray on root from 3.26.1 to 3.35...
Nothing to be done
An error ocurred, return value: 1.
Collected errors:
ERROR: Cannot satisfy the following dependencies for v2ray:
	 start-stop-daemon

**Comment by KyonLi** [comment]
ipkg update before install

**Comment by dnvcupid** [comment]
admin@RT-AC88U:/tmp/home/root# ipkg update
Successfully terminated.
admin@RT-AC88U:/tmp/home/root# ipkg upgrade
Nothing to be done
Successfully terminated.
admin@RT-AC88U:/tmp/home/root# 

大佬能说得简单易懂点不

**Comment by KyonLi** [comment]
因为有start-stop-daemon这个依赖项，所以要先ipkg update更新本地软件包索引，再ipkg install
v2ray.ipk就可以自动从源安装依赖了。这个在readme使用方法里已经写了。

dnvcupid <notifications@github.com> 于 2018年8月15日周三 00:27写道：

**Comment by dnvcupid** [comment]
admin@RT-AC88U:/tmp/home/root# cd /tmp/
admin@RT-AC88U:/tmp# ipkg update
Successfully terminated.
admin@RT-AC88U:/tmp# ipkg install v2ray_3.35_arm.ipk 
Upgrading v2ray on root from 3.26.1 to 3.35...
Nothing to be done
An error ocurred, return value: 1.
Collected errors:
ERROR: Cannot satisfy the following dependencies for v2ray:
	 start-stop-daemon
admin@RT-AC88U:/tmp# 


ipkg update
ipkg install v2ray_[version]_[architecture].ipk

是上面的操作？

**Comment by KyonLi** [comment]
检查软件源配置
```bash
admin@RT-AC86U:/tmp/home/root# cat /opt/etc/ipkg.conf 
#Uncomment the following line for native packages feed (if any)
src/gz optware.armeabi-ng http://ipkg.nslu2-linux.org/optware-ng/buildroot-armeabi-ng
src/gz optware.asus http://nw-dlcdnet.asus.com/asusware/arm/stable
dest /opt/ /
#option verbose-wget
```

**Comment by dnvcupid** [comment]
/opt/etc/ipkg.conf 是空白文件

src/gz optware.armeabi-ng http://ipkg.nslu2-linux.org/optware-ng/buildroot-armeabi-ng
src/gz optware.asus http://nw-dlcdnet.asus.com/asusware/arm/stable
dest /opt/ /

添加以上到/opt/etc/ipkg.conf后

admin@RT-AC88U:/tmp# ipkg update
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-armeabi-ng/Packages.gz
Inflating http://ipkg.nslu2-linux.org/optware-ng/buildroot-armeabi-ng/Packages.gz
Updated list of available packages in /opt/lib/ipkg/lists/optware.armeabi-ng
Downloading http://nw-dlcdnet.asus.com/asusware/arm/stable/Packages.gz
Inflating http://nw-dlcdnet.asus.com/asusware/arm/stable/Packages.gz
Updated list of available packages in /opt/lib/ipkg/lists/optware.asus
Successfully terminated.
admin@RT-AC88U:/tmp# ipkg install v2ray_3.35_arm.ipk 
Upgrading v2ray on /opt/ from 3.26.1 to 3.35...
Installing start-stop-daemon (1.18.4-1) to /opt/...
Nothing to be done
An error ocurred, return value: 28.
Collected errors:
Only have 0 available blocks on filesystem /, pkg start-stop-daemon needs 36
admin@RT-AC88U:/tmp# ipkg upgrade
Upgrading bzip2 on /opt/ from 1.0.6-1 to 1.0.6-2...
Upgrading expat on /opt/ from 2.0.1-1 to 2.2.0-1...
Upgrading libevent on /opt/ from 2.0.20-1 to 2.0.20-3...
Upgrading libpar2 on /opt/ from 0.2-6 to 0.2-7...
Upgrading libsigc++ on /opt/ from 2.2.3-1 to 2.4.1-2...
Upgrading libstdc++ on /opt/ from 6.0.2-6 to 6.0.24-2...
Upgrading libxml2 on /opt/ from 2.7.8-1 to 2.7.8-2...
Upgrading ncurses on /opt/ from 5.7-3 to 5.7-7...
Upgrading pcre on /opt/ from 8.31-1 to 8.36-2...
Upgrading uclibc-opt on /opt/ from 0.9.28-1 to 1.0.27-2...
Upgrading wxbase on /opt/ from 2.8.12-1 to 2.8.12-2...
Upgrading zlib on /opt/ from 1.2.5-1 to 1.2.8-2...
Nothing to be done
Successfully terminated.
Collected errors:
Only have 0 available blocks on filesystem /, pkg bzip2 needs 324
Only have 0 available blocks on filesystem /, pkg expat needs 192
Only have 0 available blocks on filesystem /, pkg libevent needs 972
Only have 0 available blocks on filesystem /, pkg libpar2 needs 424
Only have 0 available blocks on filesystem /, pkg libsigc++ needs 28
Only have 0 available blocks on filesystem /, pkg libstdc++ needs 1220
Only have 0 available blocks on filesystem /, pkg libxml2 needs 4484
Only have 0 available blocks on filesystem /, pkg ncurses needs 500
Only have 0 available blocks on filesystem /, pkg pcre needs 744
Only have 0 available blocks on filesystem /, pkg uclibc-opt needs 904
Only have 0 available blocks on filesystem /, pkg wxbase needs 3584
Only have 0 available blocks on filesystem /, pkg zlib needs 212

**Comment by KyonLi** [comment]
optware环境有问题，请确认是否从官方途径激活的USB应用，如果是的话可能和机型有关，AC86U自带上面的两个源，而且可以从optware-ng源安装aria2、htop都没有出现过问题。关于安装到了`/`而不是`/opt/`[这里](/Optware/Optware-ng/issues/109)有相同的案例。

如果还是无法解决可以使用[3.26.0-1](/KyonLi/asuswrt-v2ray/archive/3.26.0-1.zip)版本的源码构建ipk包，没有本质的区别。
